- hosts: webserver

  vars:
   - ansible_connection: ssh
   - ansible_ssh_user: user
   - ansible_ssh_pass: password
   - ansible_become: yes

  tasks:
   - name: Nginx setup
     apt: pkg=nginx state=present update_cache=true

   - name: Php setup
     apt: pkg=php7.0-fpm state=present

   - name: index.html copy
     template: src=index.html.j2 dest=/var/www/html/index.html

   - name: host.php copy
     template: src=host.php.j2 dest=/var/www/html/host.php

   - name: default copy
     copy: src=default dest=/etc/nginx/sites-available/default
     
   - name: restart nginx
     service: name=nginx state=restarted